<a href="https://colab.research.google.com/github/Triveni18/JavaScript/blob/main/NumpyArrayDemo06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

# 1D Array (Vector): A single row of elements
arr1 = np.array([10, 20, 30, 40, 50])

# 2D Array (Matrix): 2 rows and 5 columns
arr2 = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]])

# 3D Array (Tensor): 3 blocks of 2x2 matrices
arr3 = np.array([
    [[10, 20], [30, 40]],
    [[50, 60], [70, 80]],
    [[90, 100], [110, 120]]
])

# Printing values and their 'shape' (dimensions)
print("1D Array:\n", arr1)
print("Shape of arr1:", arr1.shape)  # Output: (5,) -> 5 elements in 1 dimension

print("\n2D Array:\n", arr2)
print("Shape of arr2:", arr2.shape)  # Output: (2, 5) -> 2 rows, 5 columns

print("\n3D Array:\n", arr3)
print("Shape of arr3:", arr3.shape)  # Output: (3, 2, 2) -> 3 layers, 2 rows, 2 columns

1D Array:
 [10 20 30 40 50]
Shape of arr1: (5,)

2D Array:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
Shape of arr2: (2, 5)

3D Array:
 [[[ 10  20]
  [ 30  40]]

 [[ 50  60]
  [ 70  80]]

 [[ 90 100]
  [110 120]]]
Shape of arr3: (3, 2, 2)
